name: deploy-frontend-testing

on:
  push:
    branches:
      - testing
    paths-ignore:
      - '.github/**'

jobs:
  app:
    name: '[Build & Publish][QA] Frontend'
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install AWS cli
        run: |
          /usr/local/bin/aws --version

      - name: Install NodeJs dependencies
        run: |
          npm i -g @angular/cli
          npm install

      - name: QA - Build
        run: |
          npm run build:qa

      - name: QA - Upload S3
        run: |
          cd dist/cocacola-andina
          aws s3 sync . s3://b2b-frontend-qa/ --delete --region us-east-1 --debug
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.QA_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.QA_AWS_SECRET_ACCESS_KEY }}

      - name: QA - Refresh Cloudfront
        run: |
          aws cloudfront create-invalidation --distribution-id=EDCCKB7KQRDV8 --paths '/*' --debug
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.QA_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.QA_AWS_SECRET_ACCESS_KEY }}

      - name: QA - Fix Permission TyC
        run: |
          aws s3 ls s3://b2b-frontend-qa/assets/docs/tyc/ --recursive | awk '{cmd="aws s3api put-object-acl --acl public-read --bucket b2b-frontend-qa --key "$4; system(cmd)}'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.QA_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.QA_AWS_SECRET_ACCESS_KEY }}
